// AUTO-GENERATED by scripts/gen-tools.ts — do not edit. Regenerate via `bun run gen:tools`.
import { Type } from "typebox"; // peerDep resolved via pi loader
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { runBrowse, cap, classifyError } from "./lib/browse";
import { isAllowed } from "./lib/commands";
import { SCHEMA_FOR, BARE_SCHEMA } from "./lib/schemas";

const TOOLS = [
  {
    name: "gstack_goto",
    gstackCmd: "goto",
    label: "Goto",
    description: "Navigate to URL (http://, https://, or file:// scoped to cwd/TEMP_DIR)",
    schema: SCHEMA_FOR.goto,
  },
  {
    name: "gstack_back",
    gstackCmd: "back",
    label: "Back",
    description: "History back",
    schema: SCHEMA_FOR.back,
  },
  {
    name: "gstack_forward",
    gstackCmd: "forward",
    label: "Forward",
    description: "History forward",
    schema: SCHEMA_FOR.forward,
  },
  {
    name: "gstack_reload",
    gstackCmd: "reload",
    label: "Reload",
    description: "Reload page",
    schema: SCHEMA_FOR.reload,
  },
  {
    name: "gstack_url",
    gstackCmd: "url",
    label: "Url",
    description: "Print current URL",
    schema: SCHEMA_FOR.url,
  },
  {
    name: "gstack_load_html",
    gstackCmd: "load-html",
    label: "Load html",
    description: "Load HTML via setContent. Accepts a file path under safe-dirs (validated), OR --from-file <payload.json> with {\"html\":\"...\",\"waitUntil\":\"...\"} for large inline HTML (Windows argv safe).",
    schema: SCHEMA_FOR.load_html,
  },
  {
    name: "gstack_snapshot",
    gstackCmd: "snapshot",
    label: "Snapshot",
    description: "Accessibility tree with @e refs for element selection. Flags: -i interactive only, -c compact, -d N depth limit, -s sel scope, -D diff vs previous, -a annotated screenshot, -o path output, -C cursor-interactive @c refs",
    schema: SCHEMA_FOR.snapshot,
  },
  {
    name: "gstack_text",
    gstackCmd: "text",
    label: "Text",
    description: "Cleaned page text",
    schema: SCHEMA_FOR.text,
  },
  {
    name: "gstack_html",
    gstackCmd: "html",
    label: "Html",
    description: "innerHTML of selector (throws if not found), or full page HTML if no selector given",
    schema: SCHEMA_FOR.html,
  },
  {
    name: "gstack_links",
    gstackCmd: "links",
    label: "Links",
    description: "All links as \"text → href\"",
    schema: SCHEMA_FOR.links,
  },
  {
    name: "gstack_forms",
    gstackCmd: "forms",
    label: "Forms",
    description: "Form fields as JSON",
    schema: SCHEMA_FOR.forms,
  },
  {
    name: "gstack_accessibility",
    gstackCmd: "accessibility",
    label: "Accessibility",
    description: "Full ARIA tree",
    schema: SCHEMA_FOR.accessibility,
  },
  {
    name: "gstack_media",
    gstackCmd: "media",
    label: "Media",
    description: "All media elements (images, videos, audio) with URLs, dimensions, types",
    schema: SCHEMA_FOR.media,
  },
  {
    name: "gstack_console",
    gstackCmd: "console",
    label: "Console",
    description: "Console messages (--errors filters to error/warning)",
    schema: SCHEMA_FOR.console,
  },
  {
    name: "gstack_network",
    gstackCmd: "network",
    label: "Network",
    description: "Network requests",
    schema: SCHEMA_FOR.network,
  },
  {
    name: "gstack_cookies",
    gstackCmd: "cookies",
    label: "Cookies",
    description: "All cookies as JSON",
    schema: SCHEMA_FOR.cookies,
  },
  {
    name: "gstack_storage",
    gstackCmd: "storage",
    label: "Storage",
    description: "Read both localStorage and sessionStorage as JSON. With \"set <key> <value>\", write to localStorage only (sessionStorage is read-only via this command — set it with `js sessionStorage.setItem(...)`).",
    schema: SCHEMA_FOR.storage,
  },
  {
    name: "gstack_js",
    gstackCmd: "js",
    label: "Js",
    description: "Run inline JavaScript expression in the page context and return result as string. Same JS sandbox as eval; the only difference is js takes an inline expr while eval reads from a file. With --out <file>, the result is written to disk instead of returned (a base64 data URL is decoded to raw bytes unless --raw is given) — ideal for rasterizing local renders to PNG without serializing megabytes back through the CLI. --out makes the invocation a WRITE (needs write scope, never allowed over the tunnel).",
    schema: SCHEMA_FOR.js,
  },
  {
    name: "gstack_eval",
    gstackCmd: "eval",
    label: "Eval",
    description: "Run JavaScript from a file in the page context and return result as string. Path must resolve under /tmp or cwd (no traversal). Use eval for multi-line scripts; use js for one-liners. With --out <file>, the result is written to disk (base64 data URL decoded to bytes unless --raw); --out makes the invocation a WRITE (needs write scope, never allowed over the tunnel).",
    schema: SCHEMA_FOR.eval,
  },
  {
    name: "gstack_css",
    gstackCmd: "css",
    label: "Css",
    description: "Computed CSS value",
    schema: SCHEMA_FOR.css,
  },
  {
    name: "gstack_attrs",
    gstackCmd: "attrs",
    label: "Attrs",
    description: "Element attributes as JSON",
    schema: SCHEMA_FOR.attrs,
  },
  {
    name: "gstack_is",
    gstackCmd: "is",
    label: "Is",
    description: "State check on element. Valid <prop> values: visible, hidden, enabled, disabled, checked, editable, focused (case-sensitive). <sel> accepts a CSS selector OR an @ref token from a prior snapshot (e.g. @e3, @c1) — refs are interchangeable with selectors anywhere a selector is expected.",
    schema: SCHEMA_FOR.is,
  },
  {
    name: "gstack_inspect",
    gstackCmd: "inspect",
    label: "Inspect",
    description: "Deep CSS inspection via CDP — full rule cascade, box model, computed styles",
    schema: BARE_SCHEMA,
  },
  {
    name: "gstack_ux_audit",
    gstackCmd: "ux-audit",
    label: "Ux audit",
    description: "Extract page structure for UX behavioral analysis — site ID, nav, headings, text blocks, interactive elements. Returns JSON for agent interpretation.",
    schema: SCHEMA_FOR.ux_audit,
  },
  {
    name: "gstack_click",
    gstackCmd: "click",
    label: "Click",
    description: "Click element",
    schema: SCHEMA_FOR.click,
  },
  {
    name: "gstack_fill",
    gstackCmd: "fill",
    label: "Fill",
    description: "Fill input",
    schema: SCHEMA_FOR.fill,
  },
  {
    name: "gstack_select",
    gstackCmd: "select",
    label: "Select",
    description: "Select dropdown option by value, label, or visible text",
    schema: SCHEMA_FOR.select,
  },
  {
    name: "gstack_hover",
    gstackCmd: "hover",
    label: "Hover",
    description: "Hover element",
    schema: SCHEMA_FOR.hover,
  },
  {
    name: "gstack_type",
    gstackCmd: "type",
    label: "Type",
    description: "Type into focused element",
    schema: SCHEMA_FOR.type,
  },
  {
    name: "gstack_press",
    gstackCmd: "press",
    label: "Press",
    description: "Press a Playwright keyboard key against the focused element. Names are case-sensitive: Enter, Tab, Escape, ArrowUp/Down/Left/Right, Backspace, Delete, Home, End, PageUp, PageDown. Modifiers combine with +: Shift+Enter, Control+A, Meta+K. Single printable chars (a, A, 1) work too. Full key list: https://playwright.dev/docs/api/class-keyboard#keyboard-press",
    schema: SCHEMA_FOR.press,
  },
  {
    name: "gstack_scroll",
    gstackCmd: "scroll",
    label: "Scroll",
    description: "With a selector, smooth-scrolls the element into view. Without a selector, jumps to page bottom. No --by/--to amount option; for pixel-precise scrolling use `js window.scrollTo(0, N)`.",
    schema: SCHEMA_FOR.scroll,
  },
  {
    name: "gstack_wait",
    gstackCmd: "wait",
    label: "Wait",
    description: "Wait for element, network idle, or page load (timeout: 15s)",
    schema: SCHEMA_FOR.wait,
  },
  {
    name: "gstack_upload",
    gstackCmd: "upload",
    label: "Upload",
    description: "Upload file(s)",
    schema: SCHEMA_FOR.upload,
  },
  {
    name: "gstack_viewport",
    gstackCmd: "viewport",
    label: "Viewport",
    description: "Set viewport size and optional deviceScaleFactor (1-3, for retina screenshots). --scale requires a context rebuild.",
    schema: SCHEMA_FOR.viewport,
  },
  {
    name: "gstack_style",
    gstackCmd: "style",
    label: "Style",
    description: "Modify CSS property on element (with undo support)",
    schema: SCHEMA_FOR.style,
  },
  {
    name: "gstack_cleanup",
    gstackCmd: "cleanup",
    label: "Cleanup",
    description: "Remove page clutter (ads, cookie banners, sticky elements, social widgets)",
    schema: SCHEMA_FOR.cleanup,
  },
  {
    name: "gstack_cookie",
    gstackCmd: "cookie",
    label: "Cookie",
    description: "Set cookie on current page domain",
    schema: SCHEMA_FOR.cookie,
  },
  {
    name: "gstack_cookie_import",
    gstackCmd: "cookie-import",
    label: "Cookie import",
    description: "Import cookies from JSON file",
    schema: SCHEMA_FOR.cookie_import,
  },
  {
    name: "gstack_cookie_import_browser",
    gstackCmd: "cookie-import-browser",
    label: "Cookie import browser",
    description: "Import cookies from installed Chromium browsers (opens picker, or use --domain for direct import)",
    schema: SCHEMA_FOR.cookie_import_browser,
  },
  {
    name: "gstack_header",
    gstackCmd: "header",
    label: "Header",
    description: "Set custom request header (colon-separated, sensitive values auto-redacted)",
    schema: SCHEMA_FOR.header,
  },
  {
    name: "gstack_useragent",
    gstackCmd: "useragent",
    label: "Useragent",
    description: "Set user agent",
    schema: SCHEMA_FOR.useragent,
  },
  {
    name: "gstack_dialog_accept",
    gstackCmd: "dialog-accept",
    label: "Dialog accept",
    description: "Auto-accept next alert/confirm/prompt. Optional text is sent as the prompt response",
    schema: SCHEMA_FOR.dialog_accept,
  },
  {
    name: "gstack_dialog_dismiss",
    gstackCmd: "dialog-dismiss",
    label: "Dialog dismiss",
    description: "Auto-dismiss next dialog",
    schema: SCHEMA_FOR.dialog_dismiss,
  },
  {
    name: "gstack_screenshot",
    gstackCmd: "screenshot",
    label: "Screenshot",
    description: "Save screenshot. --selector targets a specific element (explicit flag form). Positional selectors starting with ./#/@/[ still work.",
    schema: SCHEMA_FOR.screenshot,
  },
  {
    name: "gstack_pdf",
    gstackCmd: "pdf",
    label: "Pdf",
    description: "Save the current page as PDF. Supports page layout (--format, --width, --height, --margins, --margin-*), structure (--toc waits for Paged.js), branding (--header-template, --footer-template, --page-numbers), accessibility (--tagged, --outline), and --from-file <payload.json> for large payloads. Use --tab-id <N> to target a specific tab.",
    schema: SCHEMA_FOR.pdf,
  },
  {
    name: "gstack_responsive",
    gstackCmd: "responsive",
    label: "Responsive",
    description: "Screenshots at mobile (375x812), tablet (768x1024), desktop (1280x720). Saves as {prefix}-mobile.png etc.",
    schema: SCHEMA_FOR.responsive,
  },
  {
    name: "gstack_diff",
    gstackCmd: "diff",
    label: "Diff",
    description: "Text diff between pages",
    schema: SCHEMA_FOR.diff,
  },
  {
    name: "gstack_prettyscreenshot",
    gstackCmd: "prettyscreenshot",
    label: "Prettyscreenshot",
    description: "Clean screenshot with optional cleanup, scroll positioning, and element hiding",
    schema: SCHEMA_FOR.prettyscreenshot,
  },
  {
    name: "gstack_download",
    gstackCmd: "download",
    label: "Download",
    description: "Download URL or media element to disk using browser cookies. Use --navigate for URLs that trigger browser downloads (CDN redirects, Content-Disposition, anti-bot protected sites)",
    schema: SCHEMA_FOR.download,
  },
  {
    name: "gstack_scrape",
    gstackCmd: "scrape",
    label: "Scrape",
    description: "Bulk download all media from page. Writes manifest.json",
    schema: SCHEMA_FOR.scrape,
  },
  {
    name: "gstack_archive",
    gstackCmd: "archive",
    label: "Archive",
    description: "Save complete page as MHTML via CDP",
    schema: SCHEMA_FOR.archive,
  },
  {
    name: "gstack_tabs",
    gstackCmd: "tabs",
    label: "Tabs",
    description: "List open tabs",
    schema: SCHEMA_FOR.tabs,
  },
  {
    name: "gstack_tab",
    gstackCmd: "tab",
    label: "Tab",
    description: "Switch to tab",
    schema: SCHEMA_FOR.tab,
  },
  {
    name: "gstack_newtab",
    gstackCmd: "newtab",
    label: "Newtab",
    description: "Open new tab. With --json, returns {\"tabId\":N,\"url\":...} for programmatic use (make-pdf).",
    schema: SCHEMA_FOR.newtab,
  },
  {
    name: "gstack_closetab",
    gstackCmd: "closetab",
    label: "Closetab",
    description: "Close tab",
    schema: SCHEMA_FOR.closetab,
  },
  {
    name: "gstack_frame",
    gstackCmd: "frame",
    label: "Frame",
    description: "Switch to iframe context (or main to return)",
    schema: SCHEMA_FOR.frame,
  },
  {
    name: "gstack_state",
    gstackCmd: "state",
    label: "State",
    description: "Save/load browser state (cookies + URLs)",
    schema: SCHEMA_FOR.state,
  },
  {
    name: "gstack_skill",
    gstackCmd: "skill",
    label: "Skill",
    description: "Run a browser-skill: deterministic Playwright script that drives the daemon over loopback HTTP. 3-tier lookup (project > global > bundled). Spawned scripts get a per-spawn scoped token (read+write only) — never the daemon root token.",
    schema: SCHEMA_FOR.skill,
  },
  {
    name: "gstack_handoff",
    gstackCmd: "handoff",
    label: "Handoff",
    description: "Open visible Chrome at current page for user takeover",
    schema: SCHEMA_FOR.handoff,
  },
  {
    name: "gstack_resume",
    gstackCmd: "resume",
    label: "Resume",
    description: "Re-snapshot after user takeover, return control to AI",
    schema: SCHEMA_FOR.resume,
  },
];

/** Build CLI arg array from LLM-supplied typed params. Positional/flag mapping. */
export function buildArgs(cmd: string, params: any): string[] {
  const args: string[] = [];

  // Positional helpers
  const target = params.selector ?? params.ref;

  switch (cmd) {
    case "goto":
      args.push(params.url);
      break;

    case "load-html":
      if (params.file) args.push(params.file);
      if (params.waitUntil) {
        args.push("--wait-until", params.waitUntil);
      }
      if (params.tabIndex !== undefined) {
        args.push("--tab-id", String(params.tabIndex));
      }
      break;

    case "click":
    case "hover":
    case "links":
    case "forms":
    case "accessibility":
      if (target) args.push(target);
      break;

    case "fill":
      if (target) args.push(target);
      args.push(params.value);
      break;

    case "select":
      if (target) args.push(target);
      args.push(params.value);
      break;

    case "type":
      args.push(params.text);
      break;

    case "press":
      args.push(params.key);
      break;

    case "scroll":
      if (target) args.push(target);
      break;

    case "wait":
      if (params.selector) args.push(params.selector);
      else if (params.networkidle) args.push("--networkidle");
      else if (params.load) args.push("--load");
      break;

    case "upload":
      if (target) args.push(target);
      if (params.files) args.push(...params.files);
      break;

    case "viewport":
      if (params.size) args.push(params.size);
      if (params.scale !== undefined) args.push("--scale", String(params.scale));
      break;

    case "cookie":
      args.push(params.nameValue);
      break;

    case "cookie-import":
      args.push(params.json);
      break;

    case "cookie-import-browser":
      if (params.browser) args.push(params.browser);
      if (params.domain) args.push("--domain", params.domain);
      break;

    case "header":
      args.push(params.nameValue);
      break;

    case "useragent":
      args.push(params.string);
      break;

    case "dialog-accept":
      if (params.text) args.push(params.text);
      break;

    case "text":
    case "html":
      if (params.selector) args.push(params.selector);
      break;

    case "media":
      if (params.images) args.push("--images");
      if (params.videos) args.push("--videos");
      if (params.audio) args.push("--audio");
      if (params.selector) args.push(params.selector);
      break;

    case "js":
      args.push(params.expr);
      if (params.out) args.push("--out", params.out);
      if (params.raw) args.push("--raw");
      break;

    case "eval":
      args.push(params.file);
      if (params.out) args.push("--out", params.out);
      if (params.raw) args.push("--raw");
      break;

    case "css":
      args.push(params.selector, params.prop);
      break;

    case "attrs":
      if (target) args.push(target);
      break;

    case "is":
      args.push(params.prop);
      if (target) args.push(target);
      break;

    case "console":
      if (params.clear) args.push("--clear");
      if (params.errors) args.push("--errors");
      break;

    case "network":
      if (params.clear) args.push("--clear");
      break;

    case "storage":
      if (params.setKey && params.setValue !== undefined) {
        args.push("set", params.setKey, params.setValue);
      }
      break;

    case "style":
      if (params.undo) {
        args.push("--undo");
        if (params.undoN !== undefined) args.push(String(params.undoN));
      } else {
        if (target) args.push(target);
        args.push(params.prop, params.value);
      }
      break;

    case "cleanup":
      if (params.ads) args.push("--ads");
      if (params.cookies) args.push("--cookies");
      if (params.sticky) args.push("--sticky");
      if (params.social) args.push("--social");
      if (params.all) args.push("--all");
      break;

    case "snapshot":
      if (params.interactive) args.push("-i");
      if (params.compact) args.push("-c");
      if (params.depth !== undefined) args.push("-d", String(params.depth));
      if (params.selector) args.push("-s", params.selector);
      if (params.diff) args.push("-D");
      if (params.annotate) args.push("-a");
      if (params.outputPath) args.push("-o", params.outputPath);
      if (params.cursorInteractive) args.push("-C");
      if (params.heatmap) args.push("-H", params.heatmap);
      break;

    case "screenshot":
      if (params.viewport) args.push("--viewport");
      if (params.clip) args.push("--clip", params.clip);
      if (params.base64) args.push("--base64");
      // screenshot usage allows selector and output path as positionals
      if (target) args.push(target);
      if (params.path) args.push(params.path);
      break;

    case "pdf":
      if (params.path) args.push(params.path);
      if (params.format) args.push("--format", params.format);
      if (params.width) args.push("--width", params.width);
      if (params.height) args.push("--height", params.height);
      if (params.margins) args.push("--margins", params.margins);
      if (params.pageNumbers) args.push("--page-numbers");
      if (params.tagged) args.push("--tagged");
      if (params.outline) args.push("--outline");
      if (params.printBackground) args.push("--print-background");
      if (params.tabIndex !== undefined) {
        args.push("--tab-id", String(params.tabIndex));
      }
      break;

    case "responsive":
      if (params.prefix) args.push(params.prefix);
      break;

    case "diff":
      args.push(params.url1, params.url2);
      break;

    case "download":
      if (target) args.push(target);
      if (params.path) args.push(params.path);
      if (params.base64) args.push("--base64");
      if (params.navigate) args.push("--navigate");
      break;

    case "scrape":
      args.push(params.kind);
      if (params.selector) args.push("--selector", params.selector);
      if (params.dir) args.push("--dir", params.dir);
      if (params.limit !== undefined) args.push("--limit", String(params.limit));
      break;

    case "archive":
      if (params.path) args.push(params.path);
      break;

    case "tab":
      args.push(String(params.id));
      break;

    case "newtab":
      if (params.url) args.push(params.url);
      if (params.json) args.push("--json");
      break;

    case "closetab":
      if (params.id !== undefined) args.push(String(params.id));
      break;

    case "frame":
      if (params.main) {
        args.push("main");
      } else {
        if (params.name) args.push("--name", params.name);
        else if (params.url) args.push("--url", params.url);
        else if (target) args.push(target);
      }
      break;

    case "state":
      args.push(params.action, params.name);
      break;

    case "skill":
      args.push(params.action);
      if (params.name) args.push(params.name);
      if (params.arg) {
        for (const kv of params.arg) args.push("--arg", kv);
      }
      if (params.timeoutSec !== undefined) {
        args.push(`--timeout=${params.timeoutSec}s`);
      }
      break;

    case "prettyscreenshot":
      if (params.scrollTo) args.push("--scroll-to", params.scrollTo);
      if (params.cleanup) args.push("--cleanup");
      if (params.hide) {
        for (const s of params.hide) args.push("--hide", s);
      }
      if (params.width !== undefined) args.push("--width", String(params.width));
      if (params.path) args.push(params.path);
      break;

    case "handoff":
      if (params.message) args.push(params.message);
      break;
  }

  // Fallback / Append rare/extra flags verbatim if supplied.
  if (params.extraArgs) {
    args.push(...params.extraArgs);
  }

  return args;
}

export function registerGstackTools(pi: ExtensionAPI) {
  for (const t of TOOLS) {
    pi.registerTool({
      name: t.name,
      label: t.label,
      description: t.description,
      parameters: t.schema,
      async execute(toolCallId, params: any, signal, onUpdate, ctx) {
        if (!isAllowed(t.gstackCmd)) {
          return {
            isError: true,
            content: [{ type: "text", text: `unknown command: ${t.gstackCmd}` }],
            details: {},
          };
        }

        // Validate targets: click, fill, select, hover, links, forms, accessibility, attrs, is, upload, screenshot, download, frame, prettyscreenshot, style
        // exactly one of ref or selector required if both declared.
        // We do this check only if the schema allows both fields.
        const declaresTgt = ("ref" in params || "selector" in params) &&
          !["text", "html", "media", "wait", "snapshot", "scrape"].includes(t.gstackCmd); // exclusion exceptions

        if (declaresTgt) {
          const hasRef = params.ref !== undefined && params.ref !== "";
          const hasSel = params.selector !== undefined && params.selector !== "";
          if (hasRef && hasSel) {
            return {
              isError: true,
              content: [{ type: "text", text: "Error: Both 'ref' and 'selector' supplied. Provide exactly one target." }],
              details: {},
            };
          }
          if (!hasRef && !hasSel) {
            // Wait, screenshot allow empty target (meaning full page). Others require it.
            const optionalTgt = ["screenshot", "download", "prettyscreenshot"].includes(t.gstackCmd);
            if (!optionalTgt) {
              return {
                isError: true,
                content: [{ type: "text", text: "Error: Target required. Provide either 'ref' or 'selector'." }],
                details: {},
              };
            }
          }
        }

        // Gate: cookie-import-browser needs UI confirmation to prevent silent credential theft
        if (t.gstackCmd === "cookie-import-browser") {
          const domainInfo = params.domain ? ` for domain "${params.domain}"` : "";
          const ok = await ctx.ui.confirm(
            "Cookie Import Confirmation",
            `Allow gstack to read local browser cookies${domainInfo}? This can leak your credentials.`
          );
          if (!ok) {
            return {
              isError: true,
              content: [{ type: "text", text: "gstack cookie-import-browser blocked by user confirmation." }],
              details: {},
            };
          }
        }

        const builtArgs = buildArgs(t.gstackCmd, params);
        const { stdout, stderr, code } = await runBrowse(t.gstackCmd, builtArgs, {
          signal,
          timeoutMs: params.timeoutMs,
        });

        if (code !== 0) {
          const msg = classifyError(stderr, builtArgs);
          return {
            isError: true,
            content: [{ type: "text", text: `gstack ${t.gstackCmd} (exit ${code}):\n${msg}` }],
            details: { code, rawStderr: stderr },
          };
        }

        const { body } = cap(stdout, params);
        return {
          content: [{ type: "text", text: body }],
          details: { code },
        };
      },
    });
  }
}
